ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:toc: macro

= S3 Restructure Lambda

This Lambda function responds to S3 bucket notifications and will copy the
objects to a new directory structure based on the rules defined in environment
variables.

toc::[]

== Building

Building and testing the Lambda can be done with cargo: `cargo test build`.

In order to deploy this in AWS Lambda, it must first be built with the `cargo
lambda` command line tool, e.g.:

[source,bash]
----
cargo lambda build --release --output-format zip
----

This will produce the file: `target/lambda/lambda-delta-optimize/bootstrap.zip`

== Infrastructure

The `deployment.tf` file contains the necessary Terraform to provision the
function, a DynamoDB table for locking, and IAM permissions. This Terraform
does *not* provision an S3 bucket to optimize.

After configuring the necessary authentication for Terraform, the following
steps can be used to provision:

[source,bash]
----
cargo lambda build --release --output-format zip
terraform init
terraform plan
terraform apply
----

[NOTE]
====
Terraform configures the Lambda to run with the smallest amount of memory allowed. For a sizable table, this may not be sufficient for larger tables.
====

=== Environment variables

The following environment variables must be set for the function to run properly

|===
| Name | Value | Notes

| `INPUT_PATTERN`
| _required but empty by default_
| A prefix mapping that is compatible with the link:https://docs.rs/routefinder/0.5.3/routefinder/[routefinder] syntax, e.g. `some/prefix/with/:name/:filename` which makes the `name` and `filename`  parameters available in the output path.

| `OUTPUT_PATTERN`
| _required byt empty by default_
| A routefinder compatiblee path for rewriting the objects which match the `INPUT_MATCH` pattern, e.g. `archive/:name/:filename`

|===

[WARNING]
====
The parameters must all be present and match in the input and output patterns.
If there are variable segments of the `INPUT_PATTERN` which must be ignored, use the
special `:ignore` parameter name to ignore that segment but still allow it to match the output pattern
====

== Licensing

This repository is intentionally licensed under the link:https://www.gnu.org/licenses/agpl-3.0.en.html[AGPL 3.0]. If your organization is interested in re-licensing this function for re-use, contact me via email for commercial licensing terms: `rtyler@buoyantdata.com`

